---
- hosts:
    - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  roles:
    - ubuntu
  tasks:
    - name: Enable Wake on Lan for default NIC
      tags: wol
      block:
        - name: Install ethtool
          ansible.builtin.apt:
            name: ethtool
            state: present
            update_cache: true
            cache_valid_time: 3600
            autoclean: true
            autoremove: true

        - name: Enable Wake on Lan on default NIC
          ansible.builtin.command: ethtool -s {{ ansible_default_ipv4.interface }} wol g
          register: wol_change_result
          changed_when: False
          failed_when: 'wol_change_result.stderr != ""'

        - name: Ensure that WoL is enabled for default NIC
          ansible.builtin.command: ethtool {{ ansible_default_ipv4.interface }}
          register: current_wol_config
          changed_when: False
          failed_when: '"Wake-on: g" not in current_wol_config.stdout'
